import DashHeader from '@/components/dashboard/DashHeader';
import PageName from '@/components/dashboard/PageName';
import SidebarItems from '@/components/sidebar/SidebarItems';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DashLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section id="dash" className="flex bg-gray-100 min-h-screen">
      <Toaster position="top-center" />
      <SidebarItems />
      <div className="flex-grow text-gray-800">
        <DashHeader />
        <PageName />
        <div className="flex w-full h-screen justify-center overflow-scroll">
          {children}
        </div>
      </div>
    </section>
  );
}
